### PR TITLE
Redirect to S3 instead of proxying files.

### PR DESCRIPTION
**Pull request by skullydazed**

### CODE REVIEW

**Review by yanfali — APPROVED** [review]
Does this require changes in UI code?

**Comment by skullydazed** [comment]
No, this one should be transparent. https://github.com/qmk/qmk_compiler/pull/35 will change what the UI sees but I don't believe that requires any changes either.

**Comment by yanfali** [comment]
> No, this one should be transparent. [qmk/qmk_compiler#35](https://github.com/qmk/qmk_compiler/pull/35) will change what the UI sees but I don't believe that requires any changes either.

I'm more worried about the change in the status flag. is_failed looks like a boolean rather than a string

**Comment by skullydazed** [comment]
The code you're looking at is all client side code, consuming the same object the UI does. That object hasn't changed, I've just changed to checking a different key when waiting for results.

**Pull request merged**
